### ISSUE TITLE
Updated new wallet, Coins are in Maturing status

### ISSUE THREAD

**Issue by JacKaL424** [sparklecoin/sparklecoin#10]
Why are my coins in maturing status in the wallet instead of available?  I've had them since Sep 2017.

**Comment by SparkleCOIN-Support** [comment]
This is likely due to this very fact. Since you've had the coins for so long, they were placed into a maturing state after the new update on the blockchain took place. Typically after 90 days, and the amount of coins you have, there is a certain percentage of opportunity for your coins to mint. They will become available to transacted after 500 blocks (roughly 3 days).

**Comment by JacKaL424** [comment]
Okay.  Still dont see why they'd be available after 500 blocks, basically taking away coins I had.
